### PR TITLE
fix: editor lint & autocomplete positions

### LINKED ISSUE #352: Highlight JS code errors in `CodeEditor`
Variables injection is working fine, but the code itself is not executed.

image
image
image

### PR DESCRIPTION
**Pull request by b4s36t4**
/claim #352

fixes #352 

Solves issue with JS code liniting and autocomplete suggestions position fix.

### Summary by CodeRabbit

- New Feature: Enhanced the code editor component in our builder application. This update introduces a new JavaScript linting feature, which helps users write cleaner and more efficient code by highlighting potential issues and errors in real-time. This feature is automatically enabled based on the language you're coding in, making the process seamless and intuitive. This improvement aims to boost user productivity and code quality, enhancing the overall user experience.

### CODE REVIEW

**Comment by b4s36t4** [comment]
This does show error with variables syntax.

**Comment by b4s36t4** [comment]
I don't think it's possible. The stylings for the error is by codemirror itself. Also it depends on the container if you see the screenshot the error doesn't contain any space to make it one line.

**Comment by baptisteArno** [comment]
It should be customizable! It's all CSS in the end 🙏

**Comment by baptisteArno** [comment]
> @baptisteArno isn't going to weird if online error moves out of the container (Block)?

Nothing weird, it's a tooltip, it's meant to be floating right?

**Pull request closed without merging**
