### PR TITLE
🌐 Split pt translation into pt (EU) and pt_BR (Brazil)

### PR DESCRIPTION
**Pull request by dhanielo**
- Add support to the language nuances between European Portuguese 🇪🇺🇵🇹 and Brazilian Portuguese 🇧🇷.
- Improve coverage for "pt", "pt_BR" languages to the builder editor
- Implements i18n fallback to "en" when translations are missing

### CODE REVIEW

**Comment by baptisteArno** [comment]
Can you merge your other PR (#698) with this one?

**Comment by dhanielo** [comment]
> Can you merge your other PR (#698) with this one?

Yes, I can. I'm just adding more translations in the code, and after that, I'll merge both. 💪

**Comment by baptisteArno** [comment]
That's awesome thank you! Let me know if you need help with that :)

**Comment by dhanielo** [comment]
> That's awesome thank you! Let me know if you need help with that :)

Hi @baptisteArno I'm still working on it however may you take a look to guarantee it's going in the right way once this PR can be a bit huge?

**Comment by baptisteArno** [comment]
That looks good but I need to take a closer look. Can we avoid translating the entire app? Can we stop at some point and continue in another pull request so that it's easier to digest?

Let me know

**Comment by dhanielo** [comment]
> Yes sounds good, on this PR I tried to focus on the editor and add the fallback to en. We can stop at this point and I can create other PR to continue 💪🏼

**Comment by dhanielo** [comment]
> That looks good but I need to take a closer look. Can we avoid translating the entire app? Can we stop at some point and continue in another pull request so that it's easier to digest?
> 
> Let me know

**Comment by dhanielo** [comment]
> Yes sounds good, on this PR I tried to focus on the editor and add the fallback to en. We can stop at this point and I can create other PR to continue 💪🏼

Yes sounds good, on this PR I tried to focus on the editor and add the fallback to en. We can stop at this point and I can create other PR to continue 💪🏼

**Comment by dhanielo** [comment]
> That looks good but I need to take a closer look. Can we avoid translating the entire app? Can we stop at some point and continue in another pull request so that it's easier to digest?
> 
> Let me know

Yes sounds good, on this PR I tried to focus on the editor and add the fallback to en. We can stop at this point and I can create other PR to continue 💪🏼

**Comment by baptisteArno** [comment]
Ok, let's pause here. Let me review that!

**Comment by baptisteArno** [comment]
Had to open another PR so that I can edit some things #767

**Pull request closed without merging**
