### PR TITLE
Feature: Zemantic AI Integration

### PR DESCRIPTION
**Pull request by ezynda3**
So I've reverse engineered the best I can so far but have a few hurdles I'm trying to overcome.

1. How can I save the result of my execution to a variable of the user's choosing?
2. When I run a preview it seems like my integration block begins executing right away even if I have other blocks placed ahead of it. Any idea why that could be?

Also any tips or hints on things I'm missing so far or should be aware of would be great.

Cheers!

### CODE REVIEW

**Comment by baptisteArno** [comment]
That looks great overall!

What response field should you be able to map to variable? There's only `summary`? Or others?

> When I run a preview it seems like my integration block begins executing right away even if I have other blocks placed ahead of it. Any idea why that could be?

This is how it works, under the hood, typebot executes all the blocks before the next input block and only then it display them

**Comment by ezynda3** [comment]
For now just `summary`

**Comment by ezynda3** [comment]
I figured out the first problem. I wasn't saving the newSessionState after updating the variable. I'll be cleaning this up and hope to have something final this weekend. Thanks!

**Comment by ezynda3** [comment]
I figured out the first problem. I wasn't saving the newSessionState after updating the variable. I'll be cleaning this up and hope to have something final this weekend. Thanks!

**Comment by ezynda3** [comment]
Should be good to go!

**Comment by baptisteArno** [comment]
1. Can you add a documentation and then add the link to: [getHelpDocUrl.ts](https://github.com/baptisteArno/typebot.io/blob/033f8f99ddb72c91b46cd37cfb012ea45e23bf1e/apps/builder/src/features/graph/helpers/getHelpDocUrl.ts)
2. Rename `zemanticai` to `zenmanticAi` when possible? (File and folder names, credentials name, other?)

**Comment by ezynda3** [comment]
Updated.

I have a question though. I keep getting this error popping up in the editor whenever I initially drag the Zemantic block onto the canvas.
```
RPCClientError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "typebot",
      "groups",
      1,
      "blocks",
      0,
      "options"
    ],
    "message": "Required"
  }
]
    at TRPCClientError.from (TRPCClientError-fef6cf44.mjs:10:1)
    at eval (httpBatchLink-fbd7b43c.mjs:189:44)
```

Not sure what it means. Maybe there'e something missing in my code?

**Comment by baptisteArno** [comment]
It looks like I can't push changes to that PR.

Have you checked this option? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Review by baptisteArno — CHANGES_REQUESTED** [review]
1. The redirect link for the API token always redirect to the sign in page:

https://github.com/baptisteArno/typebot.io/assets/16015833/1186c14f-44e5-4781-a779-a8449c875f7c

2. I'd prefer that you add the same "Save answer" section for Zemantic AI instead of 2 inputs. Something like the OpenAI block:

CleanShot 2023-09-05 at 10 48 54@2x

**Comment by ezynda3** [comment]
> It looks like I can't push changes to that PR.
> 
> Have you checked this option? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

Won't let me update this for reason. I don't see the option anywhere.

**Comment by baptisteArno** [comment]
You don't see it here?

CleanShot 2023-09-06 at 08 18 37@2x

You still need to attend to the 3 points I made earlier please 🙏

**Comment by ezynda3** [comment]
Updated

**Comment by ShaheerCH** [comment]
> Updated

Hello. Really well done. It was working earlier, but it did show an error at the start. Now it does not open the initial configuration dropdown. I suggest you check that out

**Comment by baptisteArno** [comment]
All good @ezynda3, I'll add some minor UX improvements and will let you know once you can review what I did!

**Review by baptisteArno — APPROVED** [review]

**Comment by baptisteArno** [comment]
Cheers!

**Pull request merged**
