### PR TITLE
Added JS code errors in script block.

### PR DESCRIPTION
**Pull request by prateekkalra**
/claim #352

Added feature to show JS code errors in the script block like an IDE.
This PR shows the exact error unlike the other one which shows a static message. Also the error tooltip shows up in a single line over the script block popup. (The css changes in the PR are for adjusting the tooltip over the popup, which was a bit tricky)

Please find the demo video of the script block below.

https://github.com/baptisteArno/typebot.io/assets/29385192/5601223b-2e5c-4615-81b3-570d4397c4c3

### Summary by CodeRabbit

- New Feature: Integrated a JavaScript linter into the code editor, enhancing code quality by enforcing coding standards and highlighting potential issues in real-time.
- Improvement: Adjusted the maximum height of the code editor for better visibility and user experience.
- Improvement: Implemented sticky positioning for the code editor container, ensuring it remains visible while scrolling.
- New Feature: Added conditional padding and display settings to the PopoverContent and PopoverBody components, improving the visual presentation based on the block type. 

These changes aim to improve the user experience by enhancing code readability, enforcing coding standards, and improving the visual presentation of components.

### CODE REVIEW

**Comment by baptisteArno** [comment]
That's very nice.

I have several questions though.

- Why did you change the max-height of the editor?
- Why did you add padding only for script block this seems like a hack. What happens if you remove this padding?
- Does this work with CSS editor (Theme tab)?
- Does this work with JSON editor (Webhook block > Advanced config > custom body)?
- Does this work with Set variable block?

**Comment by prateekkalra** [comment]
@baptisteArno 
1. I changed the max height of editor since there was an issue when the code in the editor was very long.(Showed 2 scrollbars, and also didn't look good on smaller screens.) (Set editor max height to 400px which is the max height of the block)
2. Had to set the padding because in order to achieve a popup extend another popup, the display property of the block needed to be changed, which removed the padding. Now, to achieve this popup over popup, either I could get away with this hack, or I would have to change lot of parent classes.(Not sure if it's even possible then). (It only affects the script block)
3., 4., 5. The css editor, json editor and set variable block work as before. There won't be any change since the scope of this issue was highlighting JS code errors in the code editor.

**Comment by baptisteArno** [comment]
Thank you for the clarification!

It seems it does not work properly with Typebot's variables templating system:

This can be a valid script:

CleanShot 2023-10-25 at 18 15 34@2x

**Comment by baptisteArno** [comment]
> It seems it does not work properly with Typebot's variables templating system:

@prateekkalra Did you have the time to check this?

**Comment by prateekkalra** [comment]
@baptisteArno I checked it. Sorry, there's no straightforward way to whitelist template variables as valid syntax. I understand, why this can be a dealbreaker 😞

**Comment by baptisteArno** [comment]
Indeed, after investigating this myself, I don't think there's a clear solution for this... Still, thank you for your work 🙏

**Pull request closed without merging**
