### PR TITLE
Locale zh cn

### PR DESCRIPTION
**Pull request by liuhuapiaoyuan**
Add Simplified Chinese translation, looking forward to having my code merged

### CODE REVIEW

**Comment by baptisteArno** [comment]
Thank you. Can you add the language in the `next.config.js` file as well?

```
i18n: {
    defaultLocale: 'en',
    locales: ['en', 'fr', 'pt', 'de'],
  }
```

**Comment by liuhuapiaoyuan** [comment]
> Can you also replace `zhCN` with `zh`?

Ok！not problem

**Comment by liuhuapiaoyuan** [comment]
@

> Can you also replace `zhCN` with `zh`?

hello， i resolve my question ！

**Comment by baptisteArno** [comment]
Hey @liuhuapiaoyuan, we migrated to Tolgee to handle translations, are you still down to translate the app to Chinese? If so you should joing the Discord: https://discord.com/invite/ymK8Q33d5Z and ask for a Tolgee invite in the contributors channel 👌

**Comment by liuhuapiaoyuan** [comment]
Of course
---- Replied Message ----
| From | Baptiste ***@***.***> |
| Date | 11/14/2023 14:51 |
| To | ***@***.***> |
| Cc | abc ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [baptisteArno/typebot.io] Locale zh cn (PR #598) |

Hey @liuhuapiaoyuan, we migrated to Tolgee to handle translations, are you still down to translate the app to Chinese? If so you should joing the Discord: https://discord.com/invite/ymK8Q33d5Z and ask for a Tolgee invite in the contributors channel

**Pull request closed without merging**
