### PR TITLE
fix graph flickering & performance improvements

### PR DESCRIPTION
**Pull request by neo773**
This PR fixes the flickering and improves the performance so panning around the graph is much smoother than before.

https://github.com/baptisteArno/typebot.io/assets/62795688/56b91e20-1eb0-44b5-9a4a-c07525c2ba48

/claim #575

### Summary by CodeRabbit

- Refactor: Improved the Graph component's scaling calculation for enhanced readability and maintenance.
- Style: Updated the Graph component's style properties to ensure better compatibility and visual performance on webkit browsers.

These changes aim to enhance the user experience by ensuring the Graph component displays consistently across different web browsers. The refactoring of the scaling calculation also makes the code easier to understand and maintain, potentially leading to quicker updates and bug fixes in the future.

### CODE REVIEW

**Comment by baptisteArno** [comment]
Hey @neo773 that seems to do the trick 🙌

I'm so sorry but I thought the bounty included this comment from the issue (https://github.com/baptisteArno/typebot.io/issues/575#issuecomment-1605502689). While setting the bounty price, I thought it included that comment as well which should be harder to fix. Really sorry for the confusing spec. I had to update the bounty price 🙏

**Comment by baptisteArno** [comment]
Can you explain what all these CSS props do? And why are you using the webkit prefix?

**Comment by neo773** [comment]
@baptisteArno 
Chromium's rendering engine was based on Webkit hence the vendor prefix
This code adjust the Z plane, the flickering was caused by Z plane not being constant.

>I thought it included that comment as well which should be harder to fix

I just saw it, it was hidden comment.

**Comment by baptisteArno** [comment]
> @baptisteArno Chromium's rendering engine was based on Webkit hence the vendor prefix This code adjust the Z plane, the flickering was caused by Z plane not being constant.
> 
> > I thought it included that comment as well which should be harder to fix
> 
> I just saw it, it was hidden comment.

Would `'-webkit-perspective': 1000` be enough then?

**Comment by neo773** [comment]
@baptisteArno I've found the other properties boost the performance by a bit.

**Pull request merged**
