### PR TITLE
Checkbox in Button/Picture Choices to return the position of the choice

### PR DESCRIPTION
**Pull request by abdullahbaa5**
A non-conflicting addition without introducing any extra variable addition for button choices and picture choices block with a checkbox to save position of the choice chosen rather than the text (or other value) of the choice.

### CODE REVIEW

**Comment by baptisteArno** [comment]
I don't understand the point of this? What's the use case?

**Comment by abdullahbaa5** [comment]
> le, provide a real case scenario

it can but like i said, if there are choices of the same name, it will cause issues.

Use case: real estate buildings.

example choices:
(Flat Newyork 5bhk) (Flat Newyork 5bhk) (Flat Newyork 4bhk) now if user chooses second option, mapping will never get it right. Even though the naming are same (the picture and description are different).

**Comment by baptisteArno** [comment]
So then it will not work with the current engine as the payload sent to the server would be:

```ts
{
  "message": "Flat Newyork 5bhk"
}
```

It will never know which one was selected. And this payload can't be change as it also need to be compatible with WhatsApp runtime. 

This is indeed problematic.

**Comment by baptisteArno** [comment]
`matchedItem.id` is not the index, it's the typebot item ID.

**Comment by abdullahbaa5** [comment]
> WhatsApp

oh right... the only reason i am creating the bots are for whatsapp so i guess this would have to be scrapped... i will just manually assign a unique id to everything in the list

**Comment by abdullahbaa5** [comment]
> `matchedItem.id` is not the index, it's the typebot item ID.

I understand but it is set as  the position of the choice so i thought there is no extra processing required

**Comment by abdullahbaa5** [comment]
it seems the whatsapp api is able to return a payload or some kind of id related to the buttons that were created, maybe we could use that to fix the whatsapp issue?

**Comment by baptisteArno** [comment]
I think the real problem is displaying non-unique names in the Buttons input. That does not really make sense for the end user. Why would he select the first "Flat Newyork 5bhk" over the third?

**Comment by abdullahbaa5** [comment]
> I think the real problem is displaying non-unique names in the Buttons input. That does not really make sense for the end user. Why would he select the first "Flat Newyork 5bhk" over the third?

understandable... maybe the foundation needs to be changed where one needs not to duplicates. I think we can close this request!

**Pull request closed without merging**
