### PR TITLE
QRcode block

### PR DESCRIPTION
**Pull request by dkashikar**
This block is able to :

1. Show a QrCode
2. Optionally link to an external url

## Summary by CodeRabbit

- **New Features**
	- Introduced QR code creation and display capabilities in the app.
	- Added a new component for rendering QR code images.

### CODE REVIEW

**Comment by baptisteArno** [comment]
Hey!

That's a nice idea 👍

The `qrcode-generator` package (https://github.com/kazuhikoarase/qrcode-generator#readme) was not update since 3 years. I'd prefer we use the most recent and popular package: https://github.com/soldair/node-qrcode

**Comment by baptisteArno** [comment]
I also think it would be better to generate the QR Code as an image URL that can be then used in an Image bubble. So that we can use this block on other environment like whatsapp

**Comment by dkashikar** [comment]
Thanks. 

> Hey!
> 
> That's a nice idea 👍
> 
> The `qrcode-generator` package (https://github.com/kazuhikoarase/qrcode-generator#readme) was not update since 3 years. I'd prefer we use the most recent and popular package: https://github.com/soldair/node-qrcode

i can rewrite using this package

> I also think it would be better to generate the QR Code as an image URL that can be then used in an Image bubble. So that we can use this block on other environment like whatsapp

super. have done this.

**Comment by baptisteArno** [comment]
@dkashikar I've renamed things to proper camel case when necessary and I also properly set up the image generation so that it is uploaded to S3 instance. Otherwise, a data URI can't be used in WhatsApp.

Thanks again for your work!

**Comment by baptisteArno** [comment]
Thanks again for your work @dkashikar. 🙏

Let me know if there's anything we can improve in terms of DX.

**Comment by dkashikar** [comment]
Thank you @baptisteArno 
I was also thinking of having a password kind of input field. Basically masking the input with *. 
I am planning to use the bot on kiosks. So having some input hidden would be a good idea.

**Comment by baptisteArno** [comment]
> Thank you @baptisteArno I was also thinking of having a password kind of input field. Basically masking the input with *. I am planning to use the bot on kiosks. So having some input hidden would be a good idea.

That would be nice, we need a system to encrypt the value then because I don't want to make the user think his value is private when it's not in reality. I'll work on that ASAP (#627)

**Pull request merged**
