### PR TITLE
Anthropic Claude Block

### PR DESCRIPTION
**Pull request by stergios-enchatted**
Hello @baptisteArno,

As we discussed in issue #1315 we created a basic implementation of Anthropic’s Claude AI block.
This block is based on the OpenAI block and shares a similar structure.

The most notable changes in this PR are:
- Added the Claude AI block.
- Added relevant documentation for the new block.
- Formatted some other source files in order to pass git pre-hook checks.

Some notes to be made:
- Currently there is no way to dynamically fetch the model’s versions since there is no endpoint provided by the SDK.
  - All pre version-3 Claude models are hard-coded constant variables.
  - We have opened an issue for that on the SDK repository [here](https://github.com/anthropics/anthropic-sdk-typescript/issues/313).
- We can implement in a new PR Claude’s new [Vision system](https://docs.anthropic.com/claude/docs/vision) which allows for image analysis and understanding.
  - This can be done in a later phase, given that you agree of course.

## Summary by CodeRabbit

- **New Features**
	- Introduced the Anthropic block for creating chat messages with Claude AI in Typebot.
	- Added functionality to create chat messages using Anthropic AI SDK with configurable options.
	- Implemented encrypted credentials for Anthropic account integration.
	- Added constants and helpers for better handling of chat messages with Anthropic models.
	- Included Anthropic block in the list of enabled and forged blocks for broader access.

### CODE REVIEW

**Comment by baptisteArno** [comment]
Thank you for this amazing work 👍

Can you provide push access? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by stergios-enchatted** [comment]
Thanks @baptisteArno
It appears that this setting is not available for Github accounts that belong to an organization (https://github.com/orgs/community/discussions/5634). Have no idea why...
Anyway, to make things easier, we are inviting you to the fork, so you can have full access.

**Comment by baptisteArno** [comment]
@coderabbitai review

**Comment by baptisteArno** [comment]
Alright, I've added a few fixes, they are all separated in clear commits. Feel free to check them out. Does it look good to you?

**Review by baptisteArno — APPROVED** [review]

**Pull request merged**
