### PR TITLE
feat: add Google Tag Manager

### PR DESCRIPTION
**Pull request by Jorgelig**
This pull request adds Google Tag Manager to the application. With Tag Manager, you can manage and control tracking tags on your website without having to modify the source code. This allows you to measure the performance of your website and collect data to improve performance and user experience. In addition, Tag Manager allows you to easily implement new tags and integrations with other marketing and analytics tools without having to redeploy the application code.

image
image

### CODE REVIEW

**Comment by baptisteArno** [comment]
That's pretty cool, thank you so much for this 🙏

Same thing, I'll need to add some things, and docs as well 👌

**Comment by baptisteArno** [comment]
We're missing this part:

CleanShot 2022-12-19 at 07 56 07@2x

Isn't it important?

**Comment by Jorgelig** [comment]
You're absolutely right, it seems like a good place to move both scripts is apps\viewer\src\pages\_document.tsx.

Where do you think is the best option to implement?

**Comment by baptisteArno** [comment]
I just wanted to make sure we also need to add this. I'll push something today and let you know 👌

**Comment by baptisteArno** [comment]
Check out https://github.com/baptisteArno/typebot.io/pull/185/commits/ba5188e24f7c92b2c18468ece1ff66ac7cdbccff, let me know if it's ok with you 👍

**Comment by Jorgelig** [comment]
> Check out [ba5188e](https://github.com/baptisteArno/typebot.io/commit/ba5188e24f7c92b2c18468ece1ff66ac7cdbccff), let me know if it's ok with you 👍

it's very good for me

**Pull request merged**
