### PR TITLE
:sparkles: Introducing The Forge

### LINKED ISSUE #380: Better Integration architecture for easier contributions
You need a better Integration architecture for easily integrations.
like zapier, developers can create a integration node, and describe the schema, then zapier can render a integration node by the predefined schema.

More about dynamic extensions, You can refer to another related open source software n8n. (https://github.com/n8n-io/n8n)

### PR DESCRIPTION
**Pull request by baptisteArno**
The Forge allows anyone to easily create their own Typebot Block.

Closes #380

### CODE REVIEW

**Comment by lgertel** [comment]
This is awesome! Just taking a look. Saw that you are publishing right now.
calCom is not using basicOptions.

Do you have any idea when this release will go to main?

**Comment by baptisteArno** [comment]
> This is awesome! Just taking a look. Saw that you are publishing right now. calCom is not using basicOptions.
> 
> Do you have any idea when this release will go to main?

What do you mean by basicOptions?

I'm trying to merge it ASAP hopefully today!

**Comment by lgertel** [comment]
Sorry man! I made a mess lol.
On the last version, foge/chatNode/actions/sendMessage.ts was trying to load `baseOptions` but it didn't exist.

**Comment by lgertel** [comment]
Do you need help with documentation or something?

**Comment by baptisteArno** [comment]
@lgertel Thanks that's appreciated!

I'll do a first run on the docs soon and if you find any room for improvements that'd be awesome.

**Pull request merged**
