### PR TITLE
Made bubble height width configurable through props.

### PR DESCRIPTION
**Pull request by prateekkalra**
/claim #458
Made bubble height width configurable through props.

Please find default height width screenshot below.

image

### Summary by CodeRabbit

- New Feature: Introduced customizable dimensions for chat bubbles. Users can now specify the height and width of the chat bubbles, providing greater flexibility in adapting the chat interface to different layouts and designs. If no dimensions are specified, the system will use default values, ensuring a consistent user experience. This update enhances the visual adaptability of our chat feature, making it more user-friendly and versatile for various display settings.

### CODE REVIEW

**Review by baptisteArno — CHANGES_REQUESTED** [review]
Here is what I have as default size:

CleanShot 2023-10-18 at 15 13 42@2x

**Comment by prateekkalra** [comment]
The difference in images might be due to screen resolution. 
The default width should be same as what it is right now, in the live version ? Is it not ?

**Comment by baptisteArno** [comment]
> The difference in images might be due to screen resolution. The default width should be same as what it is right now, in the live version ? Is it not ?

Width is ok in my screenshot, it's the height that is not! Please checkout the main branch to check the default styling 🙏

**Comment by prateekkalra** [comment]
Sure @baptisteArno 
Will fix it.Thanks 🙂

**Comment by prateekkalra** [comment]
Hi @baptisteArno 
I checked again, the height in both the main branch and my branch looks exactly similar.
Did you check out this branch and test?

**Comment by baptisteArno** [comment]
It should look like this by default:

CleanShot 2023-10-20 at 07 53 00@2x

**Comment by prateekkalra** [comment]
@baptisteArno You were right about the height issue. It was looking same for me, because of the smaller resolution in my laptop. Pushed a fix to align the default height with main branch. Removed max-height, since it's already been taken care by the tailwind class.
Let me know if you still have any issues.
Thank you 🙂

**Comment by baptisteArno** [comment]
Sorry the issue lacked some context and clear scope. I'll close this as it does not fully satisfy what I was thinking about 🙏

**Pull request closed without merging**
